// ─── MELIENS SHORTFORM TYPES ───

export const SF_TYPES = {
  A: {
    id: 'A', label: '페인포인트 자극형', badge: '전환율 최고',
    color: '#f87171', icon: '🎯',
    structure: '문제 상황 클로즈업 → 제품 등장 → Before/After → 가격+CTA',
    axes_pattern: 'WHO + PAIN 중심 (2축)',
    example: '니트 즐겨입는 직장인 + 옷이 낡아보여서 스트레스',
  },
  B: {
    id: 'B', label: '기능 증명형', badge: '신뢰도 최고',
    color: '#60a5fa', icon: '🔬',
    structure: '실험/비교/테스트 → 수치 증명 → 결과 → CTA',
    axes_pattern: 'PAIN + 제품 강점 중심 (기능 소구)',
    example: '거치대가 흔들리는 문제 + 과속방지턱 테스트',
  },
  C: {
    id: 'C', label: '상황 제안형', badge: '도달 범위 최고',
    color: '#34d399', icon: '🎬',
    structure: '라이프스타일 장면 → 자연스러운 제품 배치 → 공감 → CTA',
    axes_pattern: 'WHO + WHEN + WHERE (3축, 상황 중심)',
    example: '자취 1년차 + 아침 출근 전 + 원룸 세면대',
  },
}

// ─── MELIENS PRODUCT DNA DATABASE ───

export const PRODUCTS = [
  {
    id: "clenser",
    name: "실리콘 진동클렌저",
    category: "뷰티 디바이스",
    emoji: "✨",
    price: "36,900원~",
    bestseller: true,
    review_count: 1285,
    description: "12,000회 초미세진동으로 맑고 깨끗한 피부 케어",
    strengths: [
      { tag: "12,000회 초미세진동", visual: "진동 패턴 클로즈업 — 물방울 튀는 장면", impact: 95 },
      { tag: "6단계 강도 설정", visual: "버튼 조작 → 단계별 세기 변화 시연", impact: 80 },
      { tag: "0.6mm 미세모", visual: "모질 클로즈업 + 일반 클렌저 비교", impact: 85 },
      { tag: "IPX7 완전방수", visual: "샤워 중 사용 + 물세척 장면", impact: 90 },
      { tag: "카카오프렌즈 콜라보", visual: "라이언/어피치 에디션 언박싱", impact: 88 },
      { tag: "12종 컬러 라인업", visual: "컬러 풀샷 나열 + 인테리어 매칭", impact: 75 },
      { tag: "USB-C 충전", visual: "무선 사용 편의성 시연", impact: 60 },
    ],
    contexts: {
      WHO: ["뷰티 관심 대학생", "갓생러 루틴 관심자", "아침 출근 준비 직장인", "환절기 피부 고민녀", "부모님 선물 고민 자녀"],
      WHEN: ["아침 출근 30분 전", "환절기 피부 변화기", "새해 첫 주 루틴 시작", "어버이날 시즌"],
      WHERE: ["원룸 세면대 앞", "기숙사 공용 화장실", "욕실 거울 앞"],
      PAIN: ["세안 후에도 남는 잔여물", "피부 트러블이 반복됨", "실용적 선물 뭘 사야 할지 모름", "루틴 시작 뭘 사야 할지 모름"],
      NEED: ["빠르고 확실한 클렌징", "시작하기 쉬운 루틴 아이템", "선물 센스 인정", "간편한 피부 관리"],
      INTEREST: ["뷰티/스킨케어", "갓생/루틴", "ASMR", "효도/가족"],
    },
    voc_insights: [
      "리뷰 1,285건 · '피부 매끈/뽀득' 만족 반응 최다",
      "'어머니 선물' '친구한테 추천' 등 선물/입소문 구매 빈출",
      "'카카오프렌즈 귀여워서 샀다가 효과에 만족' — 디자인→효과→추천 경로",
      "'설명서 안 보고 써서 자극' — 사용법 안내 콘텐츠 니즈 존재",
      "'손으로 세안보다 위생적' — 위생 소구 강한 반응",
    ],
  },
  {
    id: "lint",
    name: "충전식 보풀제거기",
    category: "생활가전",
    emoji: "🧹",
    price: "18,900원~",
    bestseller: true,
    review_count: 2340,
    description: "급이 다른 절삭력으로 작은 보풀까지 싹!",
    strengths: [
      { tag: "급이 다른 절삭력", visual: "Before→After 극적 비교 (니트/소파)", impact: 98 },
      { tag: "3단 날 시스템", visual: "날 구조 클로즈업 + 회전 장면", impact: 85 },
      { tag: "대용량 보풀통", visual: "보풀통 가득 차는 ASMR 장면", impact: 80 },
      { tag: "의류·침구·소파 멀티", visual: "3가지 소재 연속 시연", impact: 90 },
      { tag: "Type-C 충전식", visual: "무선 자유로운 사용 장면", impact: 70 },
      { tag: "5차 완판 기록", visual: "품절 알림 + 재입고 카운트다운", impact: 92 },
      { tag: "1세대 & 프로 2종", visual: "두 모델 나란히 비교", impact: 78 },
    ],
    contexts: {
      WHO: ["니트 즐겨 입는 직장인", "자취 1년차 사회초년생", "30대 워킹맘", "옷 관리 신경쓰는 패션피플"],
      WHEN: ["겨울 니트 시즌", "주말 대청소", "아이 등원 준비 아침", "환절기 옷장 정리"],
      WHERE: ["드레스룸 거울 앞", "원룸 소파 옆", "아이 옷장 앞", "거실 침구 위"],
      PAIN: ["좋아하는 니트에 보풀이 생겨 낡아 보임", "소파 보풀이 지저분해 보임", "아이 옷에 보풀이 반복"],
      NEED: ["옷을 새것처럼 유지", "깔끔한 생활공간", "빠른 아침 준비"],
      INTEREST: ["데일리룩/패션", "자취생 꿀팁", "정리정돈/수납", "ASMR"],
    },
    voc_insights: [
      "5차 완판 · '인스타 광고 보고 샀다' 구매 경로 1위",
      "'옷감 손상 걱정했는데 없다' — 핵심 우려 해소 시 즉구매",
      "'파워가 약하다' 부정 후기 존재 — 프로 버전으로 대응 가능",
      "'보풀 먼지가 날린다' — 사용 팁 콘텐츠 기회",
    ],
  },
  {
    id: "carholder",
    name: "맥세이프 차량용 거치대",
    category: "테크 액세서리",
    emoji: "🚗",
    price: "31,900원~",
    bestseller: true,
    review_count: 1890,
    description: "어디서나 자유로운 손쉬운 부착과 360° 각도조절",
    strengths: [
      { tag: "접착+흡착 듀얼 타입", visual: "대시보드/유리 양쪽 부착 시연", impact: 90 },
      { tag: "360° 각도조절", visual: "가로↔세로 회전 원핸드 시연", impact: 85 },
      { tag: "주행중 흔들림 제로", visual: "과속방지턱/비포장 주행 테스트", impact: 95 },
      { tag: "맥세이프 원터치 장착", visual: "한 손 탈착 슬로모션", impact: 88 },
      { tag: "6차 완판 기록", visual: "재입고 알림 캡처", impact: 80 },
    ],
    contexts: {
      WHO: ["차량 통근자", "신차 구매자", "배달/영업 드라이버", "주말 드라이브 커플"],
      WHEN: ["출퇴근 시간", "차량 인테리어 세팅 시점", "장거리 운전 전", "내비 필요한 낯선 길"],
      WHERE: ["차 안 운전석", "대시보드 위", "주차장에서 세팅"],
      PAIN: ["기존 거치대가 주행중 흔들림", "차 인테리어에 안 어울림", "내비 보면서 운전 불안"],
      NEED: ["안전한 운전중 스마트폰", "프리미엄 차량 액세서리", "원터치 편의성"],
      INTEREST: ["자동차/드라이빙", "테크/가젯 리뷰", "데일리 출퇴근"],
    },
    voc_insights: [
      "6차 완판 · '과속방지턱에서도 안 흔들림' 기능 증명 리뷰 최다",
      "'맥세이프 원터치가 진짜 편하다' — 편의성 만족도 최상위",
      "'접착력이 약해질까 걱정' — 내구성 증명 콘텐츠 기회",
      "'디자인이 깔끔해서 인테리어에 안 어울리는 문제 해결' — 디자인 소구 유효",
    ],
  },
  {
    id: "ringholder",
    name: "듀얼 마그네틱 링홀더 스트랩 Pro",
    category: "테크 액세서리",
    emoji: "💍",
    price: "22,900원~",
    bestseller: false,
    review_count: 670,
    description: "스트랩 고리+거울, 업그레이드 된 완성형 디자인",
    strengths: [
      { tag: "스트랩 고리+거울 일체형", visual: "3in1 기능 전환 시연 (홀더→거울→스트랩)", impact: 90 },
      { tag: "강력 마그네틱", visual: "흔들어도 안 빠지는 스트레스 테스트", impact: 88 },
      { tag: "5가지 컬러", visual: "컬러별 폰케이스 매칭 룩", impact: 70 },
      { tag: "거치대 기능", visual: "세워놓고 영상 시청 + 영통 장면", impact: 82 },
    ],
    contexts: {
      WHO: ["폰 자주 떨어뜨리는 사람", "셀카 좋아하는 MZ세대", "커플 매칭템 찾는 연인"],
      WHEN: ["새 폰케이스 바꿀 때", "외출 준비 거울 필요할 때", "영상통화 할 때"],
      WHERE: ["카페에서 영상 시청", "지하철 한 손 사용", "화장 고칠 때 거울 필요"],
      PAIN: ["폰 자꾸 떨어뜨림", "거울 따로 들고 다니기 귀찮음", "거치대가 따로 없음"],
      NEED: ["한 손 안전 그립", "올인원 편의성", "SNS 인증샷 감성"],
      INTEREST: ["테크/가젯 리뷰", "커플/연인", "미니멀 라이프"],
    },
    voc_insights: [
      "'거울이 생각보다 유용' — 예상 밖 기능 만족이 재구매/추천 트리거",
      "'스트랩이 안정감 있다' — 그립감 소구 효과적",
      "'커플 매칭으로 2개 샀다' — 커플템 포지셔닝 유효",
      "'색상이 예뻐서 케이스랑 맞춤' — 컬러 매칭 콘텐츠 기회",
    ],
  },
  {
    id: "laptop",
    name: "초경량 접이식 노트북 거치대",
    category: "오피스 액세서리",
    emoji: "💻",
    price: "22,900원~",
    bestseller: false,
    review_count: 520,
    description: "74g 초경량, 올바른 자세를 만들어 주는 건강한 작업 환경",
    strengths: [
      { tag: "74g 초경량", visual: "저울 위 무게 측정 + 동전 비교", impact: 95 },
      { tag: "접이식 휴대", visual: "지갑 크기 비교 + 가방 수납", impact: 90 },
      { tag: "인체공학 각도", visual: "사용 전후 자세 비교 (옆면 촬영)", impact: 85 },
      { tag: "미끄럼 방지", visual: "타이핑 안정성 + 기울기 테스트", impact: 75 },
    ],
    contexts: {
      WHO: ["재택근무 프리랜서", "카페 작업족 노마드", "대학생 과제러", "목/어깨 통증 직장인"],
      WHEN: ["새 노트북 구매 직후", "재택근무 환경 세팅", "카페 작업 시"],
      WHERE: ["사무실 데스크", "카페 작업 공간", "기숙사 책상", "소파 위 무릎"],
      PAIN: ["노트북 자세가 불편함", "목/어깨 통증", "휴대할 수 있는 거치대가 없음"],
      NEED: ["작업 환경 개선", "건강한 자세 유지", "가벼운 휴대성"],
      INTEREST: ["오피스 세팅", "미니멀 라이프", "재택근무 꿀팁"],
    },
    voc_insights: [
      "'74g이 진짜 가볍다 — 저울 인증 리뷰 다수' — 무게 소구 강력",
      "'자세가 확실히 편해짐' — 인체공학 효과 체감 후기",
      "'카페에서 꺼내면 사람들이 물어봄' — 자연 바이럴 발생",
      "'미끄러지지 않아서 타이핑 안정적' — 안정성 기능 증명 가능",
    ],
  },
  {
    id: "multitap",
    name: "4구 고용량 큐브 멀티탭",
    category: "생활가전",
    emoji: "🔌",
    price: "29,900원~",
    bestseller: false,
    review_count: 430,
    description: "4구를 큐브에 담은 공간 활용 올인원 멀티탭",
    strengths: [
      { tag: "4000W 고출력", visual: "다수 기기 동시 사용 안전 시연", impact: 85 },
      { tag: "PD 30W 고속충전", visual: "충전 속도 타임랩스 비교", impact: 90 },
      { tag: "큐브 디자인 공간절약", visual: "일반 멀티탭 vs 큐브 공간 비교", impact: 88 },
      { tag: "4구+USB 올인원", visual: "6대 디바이스 동시충전 풀샷", impact: 82 },
    ],
    contexts: {
      WHO: ["자취 1년차 사회초년생", "이사 준비중인 신혼부부", "데스크 세팅 관심자"],
      WHEN: ["이사 시즌 3~4월", "새 집 꾸미기 시작", "콘센트 부족 느낄 때"],
      WHERE: ["원룸 좁은 공간", "거실 TV 뒤", "데스크 셋업 공간"],
      PAIN: ["콘센트가 항상 부족함", "멀티탭 선이 지저분함", "충전기 따로 챙기기 번거로움"],
      NEED: ["공간 효율 극대화", "깔끔한 선 정리", "고속충전 편의"],
      INTEREST: ["인테리어/홈스타일", "자취생 꿀팁", "정리정돈/수납"],
    },
    voc_insights: [
      "'큐브 디자인이 깔끔해서 인테리어에 안 튀어' — 디자인 소구 효과적",
      "'4000W라 에어프라이어까지 돌릴 수 있다' — 고출력 안심 소구",
      "'USB 충전이 되니 충전기 따로 안 사도 됨' — 올인원 만족",
      "'선이 짧아서 좀 아쉽다' — 연장선 구성 제안 기회",
    ],
  },
  {
    id: "adapter",
    name: "해외여행용 초고속 충전 멀티 어댑터",
    category: "여행 액세서리",
    emoji: "✈️",
    price: "24,900원~",
    bestseller: false,
    review_count: 380,
    description: "해외여행 초심자 필수템, 최대 2,000W 출력",
    strengths: [
      { tag: "200개국 호환", visual: "다양한 국가 콘센트 순차 시연", impact: 90 },
      { tag: "최대 2,000W 출력", visual: "드라이어 등 고출력 기기 사용", impact: 85 },
      { tag: "6대 동시충전", visual: "가족 여행 전원 디바이스 꽂기", impact: 88 },
      { tag: "PD 초고속 충전", visual: "충전 속도 숫자 비교", impact: 80 },
      { tag: "올인원 컴팩트", visual: "여행 짐 줄이기 비교 (어댑터 3개 vs 1개)", impact: 92 },
    ],
    contexts: {
      WHO: ["여행 매니아", "해외여행 초심자", "출장 잦은 비즈니스맨", "가족 해외여행 계획자"],
      WHEN: ["여름 휴가 준비기", "해외출장 전날", "여행 짐 싸는 날"],
      WHERE: ["해외여행 호텔방", "공항 라운지", "비행기 안"],
      PAIN: ["해외에서 충전기 안 맞음", "어댑터 여러 개 챙기기 번거로움", "고출력 기기 사용 불안"],
      NEED: ["해외 끊김 없는 충전", "짐 줄이기", "가족 전원 동시 충전"],
      INTEREST: ["여행/해외여행", "다이소/가성비", "미니멀 라이프"],
    },
    voc_insights: [
      "'200개국 호환이 진짜인지 유럽에서 확인' — 해외 사용 인증 리뷰 다수",
      "'드라이어 돌아가서 감동' — 고출력 기능 실증 반응",
      "'가족 4명 디바이스 동시 충전 성공' — 가족 여행 소구 유효",
      "'좀 무겁다' — 무게 vs 기능 트레이드오프 콘텐츠 기회",
    ],
  },
  {
    id: "cardwallet",
    name: "3in1 초강력 맥세이프 카드지갑",
    category: "테크 액세서리",
    emoji: "👛",
    price: "19,900원~",
    bestseller: false,
    review_count: 290,
    description: "카드지갑, 거울, 거치대 올인원으로 한 번에 해결",
    strengths: [
      { tag: "카드지갑+거울+거치대 3in1", visual: "3가지 기능 전환 시연", impact: 92 },
      { tag: "초강력 맥세이프", visual: "흔들림 없는 부착 테스트", impact: 85 },
      { tag: "5가지 신규 컬러", visual: "컬러 스와치 + 코디 매칭", impact: 75 },
      { tag: "프리미엄 가죽 질감", visual: "소재 클로즈업 + 촉감 ASMR", impact: 78 },
    ],
    contexts: {
      WHO: ["미니멀리스트", "부모님 선물 고민 자녀", "아이폰 유저 감성파"],
      WHEN: ["연말 선물 시즌", "새 폰 구매 직후", "생일/기념일 선물"],
      WHERE: ["카페에서 영상 시청", "외출 시 거울 필요할 때", "결제할 때 카드 꺼내기"],
      PAIN: ["지갑 따로 들고 다니기 귀찮음", "선물 뭘 사야 할지 모름", "케이스가 밋밋함"],
      NEED: ["올인원 편의성", "선물 센스 인정", "프리미엄 감성"],
      INTEREST: ["미니멀 라이프", "테크/가젯 리뷰", "효도/가족"],
    },
    voc_insights: [
      "'카드 3장 넣어도 넉넉' — 수납력 만족 리뷰 다수",
      "'거울이 의외로 자주 쓰게 된다' — 거울 기능 만족도 높음",
      "'부모님 선물로 드렸더니 좋아하셨다' — 선물용 구매 경로 확인",
      "'가죽 질감이 가격 대비 고급스럽다' — 프리미엄 감성 소구 유효",
    ],
  },
]

// ─── CONTEXT DIMENSIONS (6 AXES) ───

export const CONTEXT_DIMS = {
  WHO: {
    label: "타겟 페르소나",
    question: "누가 우리의 타겟인가?",
    color: "#4ecdc4",
    values: [
      "자취 1년차 사회초년생", "신혼부부", "직장인 출근러", "대학생 기숙사",
      "여행 매니아", "차량 통근자", "재택근무 프리랜서", "반려동물 집사",
      "부모님 선물 고민 자녀", "미니멀리스트", "갓생러 루틴러", "인플루언서/리뷰어",
      "30대 워킹맘", "취미생활 다이버",
    ],
  },
  WHEN: {
    label: "시간 / 시즌",
    question: "언제 이 제품이 필요한가?",
    color: "#f59e0b",
    values: [
      "아침 출근 30분 전", "환절기 피부 변화기", "이사 시즌 3~4월",
      "여름 휴가 준비기", "겨울 니트 시즌", "연말 선물 시즌",
      "봄 새학기 시작", "블프/쇼핑 이벤트", "월요일 아침",
      "퇴근 후 저녁 루틴", "주말 대청소", "장마철",
    ],
  },
  WHERE: {
    label: "장소 / 공간",
    question: "어디서 이 제품을 쓰는가?",
    color: "#60a5fa",
    values: [
      "차 안 운전석", "원룸 좁은 공간", "사무실 데스크",
      "해외여행 호텔방", "카페 작업 공간", "세면대 앞",
      "소파 위 거실", "침대 위", "비행기 안",
      "공유 오피스", "기숙사 책상", "드레스룸",
    ],
  },
  PAIN: {
    label: "페인포인트",
    question: "어떤 불편을 해결하는가?",
    color: "#f87171",
    values: [
      "세안 후에도 남는 잔여물", "옷 보풀이 지저분해 보임",
      "거치대가 주행중 흔들림", "해외에서 충전기 안 맞음",
      "책상 위 선 정리 불가", "폰 자꾸 떨어뜨림",
      "피부 트러블이 반복됨", "선물 뭘 사야 할지 모름",
      "노트북 자세가 불편함", "콘센트가 항상 부족함",
      "니트 보풀로 옷이 낡아 보임", "출근 준비 시간 부족",
    ],
  },
  NEED: {
    label: "니즈 / 욕구",
    question: "어떤 욕구를 충족하는가?",
    color: "#34d399",
    values: [
      "간편한 피부 관리", "깔끔한 외출 준비",
      "안전한 운전중 스마트폰", "해외 끊김 없는 충전",
      "작업 환경 개선", "선물 센스 인정",
      "시간 절약 루틴", "공간 효율 극대화",
      "프리미엄 라이프", "가성비 만족",
      "SNS 인증샷", "스트레스 해소",
    ],
  },
  INTEREST: {
    label: "관심사 클러스터",
    question: "어떤 관심사와 연결되는가?",
    color: "#a78bfa",
    values: [
      "뷰티/스킨케어", "자동차/드라이빙", "여행/해외여행",
      "미니멀 라이프", "정리정돈/수납", "테크/가젯 리뷰",
      "오피스 세팅", "ASMR", "다이소/가성비",
      "자취생 꿀팁", "커플/연인", "효도/가족",
      "갓생/루틴", "인테리어/홈스타일",
    ],
  },
}

// ─── SEASON CALENDAR ───

export const SEASON_DATA = [
  { month: "1월", theme: "새해 다짐 & 정리", emoji: "🎍", products: ["lint", "laptop", "clenser"], keywords: ["신년 루틴", "새해 목표", "대청소", "겨울 케어"] },
  { month: "2월", theme: "발렌타인 & 입학 준비", emoji: "💝", products: ["cardwallet", "ringholder", "clenser"], keywords: ["선물", "새학기", "커플템", "졸업"] },
  { month: "3월", theme: "봄맞이 & 새학기", emoji: "🌸", products: ["lint", "clenser", "laptop"], keywords: ["환절기", "봄옷 정리", "기숙사", "봄맞이"] },
  { month: "4월", theme: "이사 시즌 & 벚꽃", emoji: "🏠", products: ["multitap", "laptop", "carholder"], keywords: ["이사 필수템", "자취 시작", "드라이브", "신혼집"] },
  { month: "5월", theme: "가정의 달 & 효도", emoji: "🎁", products: ["clenser", "lint", "adapter"], keywords: ["어버이날", "부모님 선물", "가족 여행", "스승의날"] },
  { month: "6월", theme: "여름 준비 & 여행", emoji: "☀️", products: ["adapter", "carholder", "ringholder"], keywords: ["여름 휴가", "해외여행", "로드트립", "장마"] },
  { month: "7월", theme: "휴가 시즌 피크", emoji: "🏖️", products: ["adapter", "cardwallet", "ringholder"], keywords: ["여행 필수템", "바캉스", "짐 줄이기", "워케이션"] },
  { month: "8월", theme: "여름 막바지 & 개학", emoji: "📚", products: ["clenser", "laptop", "multitap"], keywords: ["피부 관리", "개학 준비", "데스크 세팅", "자외선 케어"] },
  { month: "9월", theme: "가을 전환 & 추석", emoji: "🍂", products: ["lint", "clenser", "cardwallet"], keywords: ["환절기", "추석 선물", "가을 패션", "니트"] },
  { month: "10월", theme: "가을 패션 & 할로윈", emoji: "🎃", products: ["lint", "ringholder", "carholder"], keywords: ["니트 시즌", "가을 드라이브", "데일리룩", "단풍"] },
  { month: "11월", theme: "블프 & 쇼핑 시즌", emoji: "🛒", products: ["clenser", "lint", "adapter", "multitap"], keywords: ["블랙프라이데이", "연말 쇼핑", "가성비", "득템"] },
  { month: "12월", theme: "연말 선물 & 크리스마스", emoji: "🎄", products: ["clenser", "cardwallet", "ringholder", "lint"], keywords: ["크리스마스 선물", "연말 파티", "효도", "연말정산"] },
]

// ─── SHORTFORM TEMPLATES ───

export const SF_TEMPLATES = {
  youtube: { name: "YouTube Shorts", icon: "▶", color: "#ff0000", maxSec: 60, ratio: "9:16" },
  instagram: { name: "Instagram Reels", icon: "◎", color: "#e1306c", maxSec: 90, ratio: "9:16" },
}

// ─── LISTENINGMIND REAL SEARCH DATA ───

export const LISTENING_MIND_DATA = {
  brand: {
    keyword: "멜리언스",
    monthly_avg: 23473,
    trend: -0.24,
    gender: { male: 28.78, female: 71.21 },
    age: { "13-19": 1.96, "20-24": 6.06, "25-29": 15.2, "30-39": 34.87, "40-49": 26.96, "50+": 14.86 },
    insight: "브랜드 검색 2024년 대비 5배 성장했으나 최근 3개월 -24% 하락. 여성 71%, 30대가 핵심.",
  },
  products: {
    clenser: {
      name: "실리콘 진동클렌저",
      keywords: [
        { keyword: "진동클렌저", monthly_avg: 9566, trend: 0.35, intent: "T" },
        { keyword: "멜리언스 진동클렌저", monthly_avg: 11610, trend: 0.93, intent: "T" },
        { keyword: "진동클렌저 추천", monthly_avg: 643, trend: -0.21, intent: "T" },
        { keyword: "진동클렌저 부작용", monthly_avg: 284, trend: -0.31, intent: "I" },
        { keyword: "진동클렌저 단점", monthly_avg: 19, trend: 1.5, intent: "I" },
      ],
      gender: { male: 25.52, female: 74.47 },
      age: { "13-19": 4.47, "20-24": 9.33, "25-29": 15.74, "30-39": 37.64, "40-49": 22.85, "50+": 9.79 },
      seasonality: "연중 고른 검색량. 7~8월 여름 피크(최대 30,000). 2024년 5~8월 급성장 후 안정화.",
      competitors: ["포레오", "메디큐브", "다이소 진동클렌저", "쥬베라"],
      search_journey: [
        "진동클렌저 → 단점 → 추천 → 멜리언스 후기/디시",
        "멜리언스 광고 → 광고모델/광고녀 → 진동클렌저 → 부작용 → 후기",
        "진동클렌저 → 단점 → 실리콘 → 다이소 → 다른용도",
      ],
      consumer_concerns: ["부작용(피부 자극, 모공 넓어짐)", "다른 용도로 사용", "효과 있는지 의문", "다이소 저가 대비 가성비"],
      community_buzz: ["디시인사이드", "더쿠", "클리앙에서 활발한 후기/토론"],
      content_insight: "광고로 유입 후 '부작용' 검색이 핵심 전환 장벽. 부작용 불안 해소 콘텐츠가 구매 전환의 키.",
    },
    lint: {
      name: "충전식 보풀제거기",
      keywords: [
        { keyword: "보풀제거기", monthly_avg: 58923, trend: -0.47, intent: "T" },
        { keyword: "보풀제거기 추천", monthly_avg: 18303, trend: -0.38, intent: "C" },
        { keyword: "멜리언스 보풀제거기", monthly_avg: 10003, trend: -0.45, intent: "T" },
        { keyword: "다이소 보풀제거기", monthly_avg: 13443, trend: -0.27, intent: "T" },
        { keyword: "글리너 보풀제거기", monthly_avg: 11410, trend: 0.41, intent: "T" },
        { keyword: "충전식 보풀제거기", monthly_avg: 800, trend: 0.2, intent: "T" },
      ],
      gender: { male: 30.64, female: 69.35 },
      age: { "13-19": 1.99, "20-24": 4.07, "25-29": 9.16, "30-39": 30.8, "40-49": 29.23, "50+": 24.66 },
      seasonality: "극명한 시즌성: 10~2월 피크(7~9만), 6~8월 바닥(1만). 겨울 니트 시즌에 집중.",
      competitors: ["다이소(저가)", "글리너(+41% 급성장)", "필립스", "아이프리(세탁소용)", "샤오미"],
      search_journey: [
        "니트 보풀/가디건 보풀/양말 보풀 → 보풀제거기 → 추천",
        "보풀제거기 추천 → 필립스/샤오미 → 다이소 비교",
        "보풀제거기 추천 → 아이프리 → 홈페이지",
        "보풀 제거하는 법 → 보풀제거기 → 추천",
      ],
      consumer_concerns: ["옷감 손상 우려", "다이소 저가 vs 프리미엄 비교", "성능(절삭력)", "충전식 vs 건전지식"],
      content_insight: "경쟁자 글리너가 +41%로 급성장 중 — 경계 필요. 다이소 대비 '옷감 안전 + 강력 절삭력' 차별화가 핵심. 시즌 10월부터 콘텐츠 집중.",
    },
    carholder: {
      name: "맥세이프 차량용 거치대",
      keywords: [
        { keyword: "맥세이프 거치대", monthly_avg: 28343, trend: -0.02, intent: "T" },
        { keyword: "차량용 거치대 추천", monthly_avg: 923, trend: -0.27, intent: "T" },
      ],
      gender: { male: 66.77, female: 33.22 },
      age: { "20-24": 4.18, "25-29": 9.58, "30-39": 30.65, "40-49": 33.95, "50+": 20.69 },
      seasonality: "비교적 연중 안정. 1~2월 신년 피크, 9~10월 아이폰 신모델 출시 시 상승.",
      competitors: ["다이소 맥세이프 거치대", "여러 중국 브랜드"],
      search_journey: [
        "멜리언스 → 맥세이프 → 차량용 거치대",
        "멜리언스 → 맥세이프 → 맥세이프 홀더 → 링홀더/그립톡/카드지갑",
      ],
      consumer_concerns: ["흔들림 여부", "접착력(떨어짐 우려)", "360도 회전 기능", "디자인과 차량 인테리어 조화"],
      content_insight: "남성 67%로 유일한 남성 중심 제품. 30~40대 남성 드라이버 타겟. 맥세이프 생태계(거치대→카드지갑→링홀더) 크로스셀 기회.",
    },
    cardwallet: {
      name: "맥세이프 카드지갑 3in1",
      keywords: [
        { keyword: "맥세이프 카드지갑", monthly_avg: 79500, trend: 0.03, intent: "T" },
      ],
      gender: { male: 44.02, female: 55.97 },
      age: { "13-19": 7.87, "20-24": 11.17, "25-29": 17.08, "30-39": 30.91, "40-49": 23.37, "50+": 9.08 },
      seasonality: "9~10월 아이폰 신모델 출시 시 최고 피크. 연중 높은 검색량 유지.",
      competitors: ["다이소 맥세이프 카드지갑", "애플 정품"],
      search_journey: [],
      consumer_concerns: ["카드 수납 개수", "자석 세기", "두께/무게"],
      content_insight: "월 7.9만 검색으로 멜리언스 전 제품 중 시장이 가장 큼. 10대~20대 비율도 높아 젊은 층 진입 제품.",
    },
    ringholder: {
      name: "듀얼 마그네틱 링홀더 Pro",
      keywords: [
        { keyword: "멜리언스 링홀더", monthly_avg: 910, trend: -0.23, intent: "T" },
      ],
      gender: { male: 44, female: 56 },
      age: { "20-24": 10, "25-29": 16, "30-39": 32, "40-49": 26, "50+": 12 },
      seasonality: "연중 안정적. 맥세이프 거치대/카드지갑과 동조.",
      competitors: [],
      search_journey: [],
      consumer_concerns: ["자석 세기", "두께"],
      content_insight: "맥세이프 거치대/카드지갑에서 유입되는 크로스셀 제품. 독립 검색량은 적지만 생태계 내 연결 효과.",
    },
    laptop: {
      name: "초경량 접이식 노트북 거치대",
      keywords: [
        { keyword: "노트북 거치대", monthly_avg: 54366, trend: 0.05, intent: "T" },
      ],
      gender: { male: 51.85, female: 48.14 },
      age: { "20-24": 7.71, "25-29": 11.35, "30-39": 28.48, "40-49": 30.14, "50+": 19.07 },
      seasonality: "1~3월 새학기/새해 피크. 연중 높은 검색량.",
      competitors: ["다이소 노트북 거치대", "모프트"],
      search_journey: [
        "노트북 거치대 추천 → 접이식 → 초경량",
        "거북목 → 노트북 거치대 → 추천",
      ],
      consumer_concerns: ["안정성(흔들림)", "무게", "각도 조절", "호환성(인치별)"],
      content_insight: "월 5.4만 검색으로 시장이 큼. 남녀 비율 거의 동등. 30~40대 직장인 + 대학생이 핵심.",
    },
    multitap: {
      name: "4구 고용량 큐브 멀티탭",
      keywords: [
        { keyword: "멀티탭", monthly_avg: 101933, trend: -0.1, intent: "T" },
        { keyword: "멀티탭 추천", monthly_avg: 7693, trend: 0.19, intent: "T" },
        { keyword: "큐브 멀티탭", monthly_avg: 8906, trend: 0.34, intent: "T" },
      ],
      gender: { male: 46.96, female: 53.03 },
      age: { "25-29": 8.99, "30-39": 24.66, "40-49": 30.31, "50+": 27.23 },
      seasonality: "7~8월 여름 피크(에어컨 등 전력 수요), 12~1월 연말 피크.",
      competitors: ["필립스", "다이소", "여행용 멀티탭"],
      search_journey: [
        "멀티탭 추천 → 큐브 멀티탭 → 비교",
        "자취 필수템 → 멀티탭 → 추천",
      ],
      consumer_concerns: ["안전성(과부하)", "디자인", "USB 포트 수", "사이즈"],
      content_insight: "큐브 멀티탭 +34% 성장세. 공간절약 니즈 증가. 40~50대 비율 높아 실용성 강조 필요.",
    },
    adapter: {
      name: "해외여행용 초고속 충전 멀티 어댑터",
      keywords: [
        { keyword: "해외여행 어댑터", monthly_avg: 960, trend: 0.74, intent: "T" },
      ],
      gender: { male: 36.65, female: 63.34 },
      age: { "30-39": 21.72, "40-49": 27.91, "50+": 32.88 },
      seasonality: "12~1월 겨울여행 시즌, 7~8월 여름휴가 시즌 피크.",
      competitors: ["일본 어댑터 추천", "여행용 멀티어댑터"],
      search_journey: [
        "해외여행 준비물 → 어댑터 → 추천",
        "일본여행 → 어댑터 → 멀티 충전기",
      ],
      consumer_concerns: ["호환 국가", "충전 속도", "크기/무게", "안전 인증"],
      content_insight: "+74% 급성장. 여행 트렌드와 연동. 50대+ 비율 33%로 높아 시니어 여행자 타겟 가능.",
    },
  },
  competitive_landscape: {
    lint_remover_threat: "글리너 보풀제거기가 월 11,410회(+41%)로 급성장. 멜리언스 보풀제거기(-45%)와 정반대 추세. 글리너 대비 차별점 강조 필요.",
    cleanser_entry: "진동클렌저 시장에서 포레오가 프리미엄, 다이소/메디큐브가 중저가 장악. 멜리언스는 '가성비 프리미엄' 포지션.",
    daiso_everywhere: "다이소가 보풀제거기, 진동클렌저, 맥세이프 카드지갑, 노트북 거치대 등 거의 모든 카테고리에서 저가 경쟁. '다이소 대비 왜 멜리언스인가'가 공통 숏폼 메시지.",
  },
  key_insights_for_shortform: [
    "진동클렌저: '부작용 불안 해소'가 전환 핵심. 숏폼에서 '피부과 전문의도 인정한 안전성' 또는 '3개월 사용 후기' 형태가 효과적.",
    "보풀제거기: 10~2월 집중. '다이소 vs 멜리언스 비교' 숏폼이 검색 니즈와 직결. '옷감 손상 없이 새 옷처럼'이 핵심 메시지.",
    "보풀제거기: 글리너 대비 포지셔닝 필요. 글리너가 급성장 중이므로 '충전식 프리미엄'의 차별점 강조.",
    "맥세이프 거치대: 남성 67% — 숏폼 톤도 남성 타겟으로. '과속방지턱 테스트' '신차 인테리어 매칭' 등 자동차 관심사 연결.",
    "맥세이프 카드지갑: 가장 큰 시장(월 7.9만). 아이폰 신모델 출시(9월) 전 콘텐츠 선제 배치.",
    "큐브 멀티탭: +34% 성장. 자취/신혼 '공간 절약' 키워드와 연결. 여름 에어컨 시즌 집중.",
    "해외여행 어댑터: +74% 급성장. 시니어 여행자(50대+ 33%) 타겟 블루오션.",
    "브랜드 전체: 디시인사이드/더쿠/클리앙이 구매 의사결정 핵심 채널. 커뮤니티 후기 기반 숏폼 유형이 효과적.",
    "경쟁 공통: 다이소가 거의 모든 카테고리에서 저가 경쟁. '왜 다이소 말고 멜리언스인가'가 숏폼의 근본 질문.",
  ],
}

// ─── DA CREATIVE 성과 데이터 ───
export const DA_CREATIVE_DATA = {
  creatives: [
    { id: "DA-001", product: "보풀제거기", channel: "GDN", type: "FOMO형", headline: "이미 사셨다면 죄송합니다", sub_copy: "20만 주부가 선택한 국민 보풀제거기", impressions: 520000, clicks: 6240, ctr: 1.2, conversions: 93, cvr: 1.49, cpa: 12800, roas: 1.6 },
    { id: "DA-002", product: "보풀제거기", channel: "GDN", type: "사회적증거형", headline: "20만 판매 보풀제거기", sub_copy: "죄송합니다 곧 정가로 돌아갑니다 공식몰 한정 최대...", impressions: 480000, clicks: 6720, ctr: 1.4, conversions: 107, cvr: 1.59, cpa: 11200, roas: 1.8 },
    { id: "DA-003", product: "차량용 거치대", channel: "GDN", type: "기능소구형", headline: "주행시 흔들림NO 차량용 거치대", sub_copy: "360도 각도 조절 차량용거치대", impressions: 310000, clicks: 4340, ctr: 1.4, conversions: 78, cvr: 1.8, cpa: 10500, roas: 2.5 },
    { id: "DA-004", product: "차량용 거치대", channel: "GDN", type: "FOMO형", headline: "이미 사셨다면 죄송합니다", sub_copy: "5차 완판 맥세이프 차량용거치대", impressions: 420000, clicks: 4620, ctr: 1.1, conversions: 55, cvr: 1.19, cpa: 14200, roas: 1.4 },
    { id: "DA-005", product: "맥세이프 카드지갑", channel: "GDN", type: "타겟소구형", headline: "붙이면 끝 맥세이프카드지갑", sub_copy: "초미녀들 주목 맥세이프카드지갑", impressions: 380000, clicks: 5700, ctr: 1.5, conversions: 114, cvr: 2.0, cpa: 8900, roas: 2.8 },
    { id: "DA-006", product: "맥세이프 카드지갑", channel: "GDN", type: "공감형", headline: "이거 없이 어떻게 살았지;;", sub_copy: "출퇴근 필수템! 가벼워져서 좋음", impressions: 290000, clicks: 4640, ctr: 1.6, conversions: 102, cvr: 2.2, cpa: 8200, roas: 3.0 },
    { id: "DA-007", product: "링홀더", channel: "GDN", type: "사회적증거형", headline: "요새 난리난 맥세이프 링홀더", sub_copy: "공식몰 단독 할인 특가 >>", impressions: 210000, clicks: 2730, ctr: 1.3, conversions: 41, cvr: 1.5, cpa: 13500, roas: 1.3 },
    { id: "DA-008", product: "해외여행 어댑터", channel: "GDN", type: "FOMO형", headline: "먼저 사신분들 죄송합니다", sub_copy: "59% 할인해요 35w 초고속 충전 멀티어댑터", impressions: 156000, clicks: 2496, ctr: 1.6, conversions: 62, cvr: 2.48, cpa: 7800, roas: 3.5 },
  ]
}
