// ─── MELIENS PRODUCT DNA DATABASE ───

export const PRODUCTS = [
  {
    id: "clenser",
    name: "실리콘 진동클렌저",
    category: "뷰티 디바이스",
    emoji: "✨",
    price: "36,900원~",
    bestseller: true,
    description: "12,000회 초미세진동으로 맑고 깨끗한 피부 케어",
    strengths: [
      { tag: "12,000회 초미세진동", visual: "진동 패턴 클로즈업 — 물방울 튀는 장면", impact: 95 },
      { tag: "6단계 강도 설정", visual: "버튼 조작 → 단계별 세기 변화 시연", impact: 80 },
      { tag: "0.6mm 미세모", visual: "모질 클로즈업 + 일반 클렌저 비교", impact: 85 },
      { tag: "IPX7 완전방수", visual: "샤워 중 사용 + 물세척 장면", impact: 90 },
      { tag: "카카오프렌즈 콜라보", visual: "라이언/어피치 에디션 언박싱", impact: 88 },
      { tag: "12종 컬러 라인업", visual: "컬러 풀샷 나열 + 인테리어 매칭", impact: 75 },
      { tag: "USB-C 충전", visual: "무선 사용 편의성 시연", impact: 60 },
    ],
    contexts: {
      WHO: ["뷰티 관심 대학생", "갓생러 루틴 관심자", "아침 출근 준비 직장인", "환절기 피부 고민녀", "부모님 선물 고민 자녀"],
      WHEN: ["아침 출근 30분 전", "환절기 피부 변화기", "새해 첫 주 루틴 시작", "어버이날 시즌"],
      WHERE: ["원룸 세면대 앞", "기숙사 공용 화장실", "욕실 거울 앞"],
      PAIN: ["세안 후에도 남는 잔여물", "피부 트러블이 반복됨", "실용적 선물 뭘 사야 할지 모름", "루틴 시작 뭘 사야 할지 모름"],
      NEED: ["빠르고 확실한 클렌징", "시작하기 쉬운 루틴 아이템", "선물 센스 인정", "간편한 피부 관리"],
      INTEREST: ["뷰티/스킨케어", "갓생/루틴", "ASMR", "효도/가족"],
    },
  },
  {
    id: "lint",
    name: "충전식 보풀제거기",
    category: "생활가전",
    emoji: "🧹",
    price: "18,900원~",
    bestseller: true,
    description: "급이 다른 절삭력으로 작은 보풀까지 싹!",
    strengths: [
      { tag: "급이 다른 절삭력", visual: "Before→After 극적 비교 (니트/소파)", impact: 98 },
      { tag: "3단 날 시스템", visual: "날 구조 클로즈업 + 회전 장면", impact: 85 },
      { tag: "대용량 보풀통", visual: "보풀통 가득 차는 ASMR 장면", impact: 80 },
      { tag: "의류·침구·소파 멀티", visual: "3가지 소재 연속 시연", impact: 90 },
      { tag: "Type-C 충전식", visual: "무선 자유로운 사용 장면", impact: 70 },
      { tag: "5차 완판 기록", visual: "품절 알림 + 재입고 카운트다운", impact: 92 },
      { tag: "1세대 & 프로 2종", visual: "두 모델 나란히 비교", impact: 78 },
    ],
    contexts: {
      WHO: ["니트 즐겨 입는 직장인", "자취 1년차 사회초년생", "30대 워킹맘", "옷 관리 신경쓰는 패션피플"],
      WHEN: ["겨울 니트 시즌", "주말 대청소", "아이 등원 준비 아침", "환절기 옷장 정리"],
      WHERE: ["드레스룸 거울 앞", "원룸 소파 옆", "아이 옷장 앞", "거실 침구 위"],
      PAIN: ["좋아하는 니트에 보풀이 생겨 낡아 보임", "소파 보풀이 지저분해 보임", "아이 옷에 보풀이 반복"],
      NEED: ["옷을 새것처럼 유지", "깔끔한 생활공간", "빠른 아침 준비"],
      INTEREST: ["데일리룩/패션", "자취생 꿀팁", "정리정돈/수납", "ASMR"],
    },
  },
  {
    id: "carholder",
    name: "맥세이프 차량용 거치대",
    category: "테크 액세서리",
    emoji: "🚗",
    price: "31,900원~",
    bestseller: true,
    description: "어디서나 자유로운 손쉬운 부착과 360° 각도조절",
    strengths: [
      { tag: "접착+흡착 듀얼 타입", visual: "대시보드/유리 양쪽 부착 시연", impact: 90 },
      { tag: "360° 각도조절", visual: "가로↔세로 회전 원핸드 시연", impact: 85 },
      { tag: "주행중 흔들림 제로", visual: "과속방지턱/비포장 주행 테스트", impact: 95 },
      { tag: "맥세이프 원터치 장착", visual: "한 손 탈착 슬로모션", impact: 88 },
      { tag: "6차 완판 기록", visual: "재입고 알림 캡처", impact: 80 },
    ],
    contexts: {
      WHO: ["차량 통근자", "신차 구매자", "배달/영업 드라이버", "주말 드라이브 커플"],
      WHEN: ["출퇴근 시간", "차량 인테리어 세팅 시점", "장거리 운전 전", "내비 필요한 낯선 길"],
      WHERE: ["차 안 운전석", "대시보드 위", "주차장에서 세팅"],
      PAIN: ["기존 거치대가 주행중 흔들림", "차 인테리어에 안 어울림", "내비 보면서 운전 불안"],
      NEED: ["안전한 운전중 스마트폰", "프리미엄 차량 액세서리", "원터치 편의성"],
      INTEREST: ["자동차/드라이빙", "테크/가젯 리뷰", "데일리 출퇴근"],
    },
  },
  {
    id: "ringholder",
    name: "듀얼 마그네틱 링홀더 스트랩 Pro",
    category: "테크 액세서리",
    emoji: "💍",
    price: "22,900원~",
    bestseller: false,
    description: "스트랩 고리+거울, 업그레이드 된 완성형 디자인",
    strengths: [
      { tag: "스트랩 고리+거울 일체형", visual: "3in1 기능 전환 시연 (홀더→거울→스트랩)", impact: 90 },
      { tag: "강력 마그네틱", visual: "흔들어도 안 빠지는 스트레스 테스트", impact: 88 },
      { tag: "5가지 컬러", visual: "컬러별 폰케이스 매칭 룩", impact: 70 },
      { tag: "거치대 기능", visual: "세워놓고 영상 시청 + 영통 장면", impact: 82 },
    ],
    contexts: {
      WHO: ["폰 자주 떨어뜨리는 사람", "셀카 좋아하는 MZ세대", "커플 매칭템 찾는 연인"],
      WHEN: ["새 폰케이스 바꿀 때", "외출 준비 거울 필요할 때", "영상통화 할 때"],
      WHERE: ["카페에서 영상 시청", "지하철 한 손 사용", "화장 고칠 때 거울 필요"],
      PAIN: ["폰 자꾸 떨어뜨림", "거울 따로 들고 다니기 귀찮음", "거치대가 따로 없음"],
      NEED: ["한 손 안전 그립", "올인원 편의성", "SNS 인증샷 감성"],
      INTEREST: ["테크/가젯 리뷰", "커플/연인", "미니멀 라이프"],
    },
  },
  {
    id: "laptop",
    name: "초경량 접이식 노트북 거치대",
    category: "오피스 액세서리",
    emoji: "💻",
    price: "22,900원~",
    bestseller: false,
    description: "74g 초경량, 올바른 자세를 만들어 주는 건강한 작업 환경",
    strengths: [
      { tag: "74g 초경량", visual: "저울 위 무게 측정 + 동전 비교", impact: 95 },
      { tag: "접이식 휴대", visual: "지갑 크기 비교 + 가방 수납", impact: 90 },
      { tag: "인체공학 각도", visual: "사용 전후 자세 비교 (옆면 촬영)", impact: 85 },
      { tag: "미끄럼 방지", visual: "타이핑 안정성 + 기울기 테스트", impact: 75 },
    ],
    contexts: {
      WHO: ["재택근무 프리랜서", "카페 작업족 노마드", "대학생 과제러", "목/어깨 통증 직장인"],
      WHEN: ["새 노트북 구매 직후", "재택근무 환경 세팅", "카페 작업 시"],
      WHERE: ["사무실 데스크", "카페 작업 공간", "기숙사 책상", "소파 위 무릎"],
      PAIN: ["노트북 자세가 불편함", "목/어깨 통증", "휴대할 수 있는 거치대가 없음"],
      NEED: ["작업 환경 개선", "건강한 자세 유지", "가벼운 휴대성"],
      INTEREST: ["오피스 세팅", "미니멀 라이프", "재택근무 꿀팁"],
    },
  },
  {
    id: "multitap",
    name: "4구 고용량 큐브 멀티탭",
    category: "생활가전",
    emoji: "🔌",
    price: "29,900원~",
    bestseller: false,
    description: "4구를 큐브에 담은 공간 활용 올인원 멀티탭",
    strengths: [
      { tag: "4000W 고출력", visual: "다수 기기 동시 사용 안전 시연", impact: 85 },
      { tag: "PD 30W 고속충전", visual: "충전 속도 타임랩스 비교", impact: 90 },
      { tag: "큐브 디자인 공간절약", visual: "일반 멀티탭 vs 큐브 공간 비교", impact: 88 },
      { tag: "4구+USB 올인원", visual: "6대 디바이스 동시충전 풀샷", impact: 82 },
    ],
    contexts: {
      WHO: ["자취 1년차 사회초년생", "이사 준비중인 신혼부부", "데스크 세팅 관심자"],
      WHEN: ["이사 시즌 3~4월", "새 집 꾸미기 시작", "콘센트 부족 느낄 때"],
      WHERE: ["원룸 좁은 공간", "거실 TV 뒤", "데스크 셋업 공간"],
      PAIN: ["콘센트가 항상 부족함", "멀티탭 선이 지저분함", "충전기 따로 챙기기 번거로움"],
      NEED: ["공간 효율 극대화", "깔끔한 선 정리", "고속충전 편의"],
      INTEREST: ["인테리어/홈스타일", "자취생 꿀팁", "정리정돈/수납"],
    },
  },
  {
    id: "adapter",
    name: "해외여행용 초고속 충전 멀티 어댑터",
    category: "여행 액세서리",
    emoji: "✈️",
    price: "24,900원~",
    bestseller: false,
    description: "해외여행 초심자 필수템, 최대 2,000W 출력",
    strengths: [
      { tag: "200개국 호환", visual: "다양한 국가 콘센트 순차 시연", impact: 90 },
      { tag: "최대 2,000W 출력", visual: "드라이어 등 고출력 기기 사용", impact: 85 },
      { tag: "6대 동시충전", visual: "가족 여행 전원 디바이스 꽂기", impact: 88 },
      { tag: "PD 초고속 충전", visual: "충전 속도 숫자 비교", impact: 80 },
      { tag: "올인원 컴팩트", visual: "여행 짐 줄이기 비교 (어댑터 3개 vs 1개)", impact: 92 },
    ],
    contexts: {
      WHO: ["여행 매니아", "해외여행 초심자", "출장 잦은 비즈니스맨", "가족 해외여행 계획자"],
      WHEN: ["여름 휴가 준비기", "해외출장 전날", "여행 짐 싸는 날"],
      WHERE: ["해외여행 호텔방", "공항 라운지", "비행기 안"],
      PAIN: ["해외에서 충전기 안 맞음", "어댑터 여러 개 챙기기 번거로움", "고출력 기기 사용 불안"],
      NEED: ["해외 끊김 없는 충전", "짐 줄이기", "가족 전원 동시 충전"],
      INTEREST: ["여행/해외여행", "다이소/가성비", "미니멀 라이프"],
    },
  },
  {
    id: "cardwallet",
    name: "3in1 초강력 맥세이프 카드지갑",
    category: "테크 액세서리",
    emoji: "👛",
    price: "19,900원~",
    bestseller: false,
    description: "카드지갑, 거울, 거치대 올인원으로 한 번에 해결",
    strengths: [
      { tag: "카드지갑+거울+거치대 3in1", visual: "3가지 기능 전환 시연", impact: 92 },
      { tag: "초강력 맥세이프", visual: "흔들림 없는 부착 테스트", impact: 85 },
      { tag: "5가지 신규 컬러", visual: "컬러 스와치 + 코디 매칭", impact: 75 },
      { tag: "프리미엄 가죽 질감", visual: "소재 클로즈업 + 촉감 ASMR", impact: 78 },
    ],
    contexts: {
      WHO: ["미니멀리스트", "부모님 선물 고민 자녀", "아이폰 유저 감성파"],
      WHEN: ["연말 선물 시즌", "새 폰 구매 직후", "생일/기념일 선물"],
      WHERE: ["카페에서 영상 시청", "외출 시 거울 필요할 때", "결제할 때 카드 꺼내기"],
      PAIN: ["지갑 따로 들고 다니기 귀찮음", "선물 뭘 사야 할지 모름", "케이스가 밋밋함"],
      NEED: ["올인원 편의성", "선물 센스 인정", "프리미엄 감성"],
      INTEREST: ["미니멀 라이프", "테크/가젯 리뷰", "효도/가족"],
    },
  },
]

// ─── CONTEXT DIMENSIONS (6 AXES) ───

export const CONTEXT_DIMS = {
  WHO: {
    label: "타겟 페르소나",
    question: "누가 우리의 타겟인가?",
    color: "#4ecdc4",
    values: [
      "자취 1년차 사회초년생", "신혼부부", "직장인 출근러", "대학생 기숙사",
      "여행 매니아", "차량 통근자", "재택근무 프리랜서", "반려동물 집사",
      "부모님 선물 고민 자녀", "미니멀리스트", "갓생러 루틴러", "인플루언서/리뷰어",
      "30대 워킹맘", "취미생활 다이버",
    ],
  },
  WHEN: {
    label: "시간 / 시즌",
    question: "언제 이 제품이 필요한가?",
    color: "#f59e0b",
    values: [
      "아침 출근 30분 전", "환절기 피부 변화기", "이사 시즌 3~4월",
      "여름 휴가 준비기", "겨울 니트 시즌", "연말 선물 시즌",
      "봄 새학기 시작", "블프/쇼핑 이벤트", "월요일 아침",
      "퇴근 후 저녁 루틴", "주말 대청소", "장마철",
    ],
  },
  WHERE: {
    label: "장소 / 공간",
    question: "어디서 이 제품을 쓰는가?",
    color: "#60a5fa",
    values: [
      "차 안 운전석", "원룸 좁은 공간", "사무실 데스크",
      "해외여행 호텔방", "카페 작업 공간", "세면대 앞",
      "소파 위 거실", "침대 위", "비행기 안",
      "공유 오피스", "기숙사 책상", "드레스룸",
    ],
  },
  PAIN: {
    label: "페인포인트",
    question: "어떤 불편을 해결하는가?",
    color: "#f87171",
    values: [
      "세안 후에도 남는 잔여물", "옷 보풀이 지저분해 보임",
      "거치대가 주행중 흔들림", "해외에서 충전기 안 맞음",
      "책상 위 선 정리 불가", "폰 자꾸 떨어뜨림",
      "피부 트러블이 반복됨", "선물 뭘 사야 할지 모름",
      "노트북 자세가 불편함", "콘센트가 항상 부족함",
      "니트 보풀로 옷이 낡아 보임", "출근 준비 시간 부족",
    ],
  },
  NEED: {
    label: "니즈 / 욕구",
    question: "어떤 욕구를 충족하는가?",
    color: "#34d399",
    values: [
      "간편한 피부 관리", "깔끔한 외출 준비",
      "안전한 운전중 스마트폰", "해외 끊김 없는 충전",
      "작업 환경 개선", "선물 센스 인정",
      "시간 절약 루틴", "공간 효율 극대화",
      "프리미엄 라이프", "가성비 만족",
      "SNS 인증샷", "스트레스 해소",
    ],
  },
  INTEREST: {
    label: "관심사 클러스터",
    question: "어떤 관심사와 연결되는가?",
    color: "#a78bfa",
    values: [
      "뷰티/스킨케어", "자동차/드라이빙", "여행/해외여행",
      "미니멀 라이프", "정리정돈/수납", "테크/가젯 리뷰",
      "오피스 세팅", "ASMR", "다이소/가성비",
      "자취생 꿀팁", "커플/연인", "효도/가족",
      "갓생/루틴", "인테리어/홈스타일",
    ],
  },
}

// ─── SEASON CALENDAR ───

export const SEASON_DATA = [
  { month: "1월", theme: "새해 다짐 & 정리", emoji: "🎍", products: ["lint", "laptop", "clenser"], keywords: ["신년 루틴", "새해 목표", "대청소", "겨울 케어"] },
  { month: "2월", theme: "발렌타인 & 입학 준비", emoji: "💝", products: ["cardwallet", "ringholder", "clenser"], keywords: ["선물", "새학기", "커플템", "졸업"] },
  { month: "3월", theme: "봄맞이 & 새학기", emoji: "🌸", products: ["lint", "clenser", "laptop"], keywords: ["환절기", "봄옷 정리", "기숙사", "봄맞이"] },
  { month: "4월", theme: "이사 시즌 & 벚꽃", emoji: "🏠", products: ["multitap", "laptop", "carholder"], keywords: ["이사 필수템", "자취 시작", "드라이브", "신혼집"] },
  { month: "5월", theme: "가정의 달 & 효도", emoji: "🎁", products: ["clenser", "lint", "adapter"], keywords: ["어버이날", "부모님 선물", "가족 여행", "스승의날"] },
  { month: "6월", theme: "여름 준비 & 여행", emoji: "☀️", products: ["adapter", "carholder", "ringholder"], keywords: ["여름 휴가", "해외여행", "로드트립", "장마"] },
  { month: "7월", theme: "휴가 시즌 피크", emoji: "🏖️", products: ["adapter", "cardwallet", "ringholder"], keywords: ["여행 필수템", "바캉스", "짐 줄이기", "워케이션"] },
  { month: "8월", theme: "여름 막바지 & 개학", emoji: "📚", products: ["clenser", "laptop", "multitap"], keywords: ["피부 관리", "개학 준비", "데스크 세팅", "자외선 케어"] },
  { month: "9월", theme: "가을 전환 & 추석", emoji: "🍂", products: ["lint", "clenser", "cardwallet"], keywords: ["환절기", "추석 선물", "가을 패션", "니트"] },
  { month: "10월", theme: "가을 패션 & 할로윈", emoji: "🎃", products: ["lint", "ringholder", "carholder"], keywords: ["니트 시즌", "가을 드라이브", "데일리룩", "단풍"] },
  { month: "11월", theme: "블프 & 쇼핑 시즌", emoji: "🛒", products: ["clenser", "lint", "adapter", "multitap"], keywords: ["블랙프라이데이", "연말 쇼핑", "가성비", "득템"] },
  { month: "12월", theme: "연말 선물 & 크리스마스", emoji: "🎄", products: ["clenser", "cardwallet", "ringholder", "lint"], keywords: ["크리스마스 선물", "연말 파티", "효도", "연말정산"] },
]

// ─── SHORTFORM TEMPLATES ───

export const SF_TEMPLATES = {
  youtube: { name: "YouTube Shorts", icon: "▶", color: "#ff0000", maxSec: 60, ratio: "9:16" },
  instagram: { name: "Instagram Reels", icon: "◎", color: "#e1306c", maxSec: 90, ratio: "9:16" },
}
